apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-mind
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-mind
  template:
    metadata:
      labels:
        app: hive-mind
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: hive-mind
          image: 859384797868.dkr.ecr.us-east-1.amazonaws.com/hive-mind:main
          imagePullPolicy: Always
          ports:
            - containerPort: 5149
          env:
            - name: CommunicationControl__Url
              value: "http://com-control:8080"
            - name: ConnectionStrings__Redis
              value: "redis:6379,abortConnect=false"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi