version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-main
    restart: always
    ports:
      - "6381:6379"
    networks:
      - hive-emulator-main
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-main
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - hive-emulator-main
    depends_on:
      redis:
        condition: service_healthy

  communication-control:
    image: 859384797868.dkr.ecr.us-east-1.amazonaws.com/communication-control:main
    container_name: communication-control-main
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Redis__ConnectionString=redis:6379,abortConnect=false
      - Redis__Host=redis
      - Redis__Port=6379
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - hive-emulator-main
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  hive-mind:
    image: 859384797868.dkr.ecr.us-east-1.amazonaws.com/hive-mind:main
    container_name: hive-mind-main
    restart: always
    environment:
      - CommunicationControl__Url=http://communication-control:8080
    networks:
      - hive-emulator-main
    depends_on:
      - redis
      - communication-control

  web:
    image: 859384797868.dkr.ecr.us-east-1.amazonaws.com/web:main
    container_name: web-main
    ports:
      - "80:80"
    volumes:
      - ./MapClient/public/config.json:/usr/share/nginx/html/config.json
    networks:
      - hive-emulator-main
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hive-emulator-main
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - hive-emulator-main
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-local
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hive-emulator-main
  promtail:
      image: grafana/promtail:latest
      volumes:
        - ./monitoring/promtail.yml:/etc/promtail/config.yml
        - /var/run/docker.sock:/var/run/docker.sock      
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
      command: -config.file=/etc/promtail/config.yml
      networks:
        - hive-emulator-main
  loki:
      image: grafana/loki:latest
      container_name: loki-main
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      networks:
        - hive-emulator-main
networks:
  hive-emulator-main:
    driver: bridge