name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_NAME: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ github.ref_name == 'main' && secrets.HOST_MAIN || secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/app
            cd ~/app
            
            FILE_NAME="docker-compose.${{ github.ref_name }}.yml"
            
            curl -L -o $FILE_NAME https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$FILE_NAME
            
            # Логін в ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 859384797868.dkr.ecr.us-east-1.amazonaws.com
            
            docker compose -f $FILE_NAME pull
            docker compose -f $FILE_NAME up -d
            
            docker image prune -f