name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Publish Services
        run: |
          dotnet publish ./src/CommunicationControl/DevOpsProject/DevOpsProject.CommunicationControl.API.csproj -c Release -o ./src/CommunicationControl/DevOpsProject/published
          dotnet publish ./src/CommunicationControl/DevOpsProject.HiveMind.API/DevOpsProject.HiveMind.API.csproj -c Release -o ./src/CommunicationControl/DevOpsProject.HiveMind.API/published

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $ECR_REGISTRY/communication-control:$IMAGE_TAG -f ./src/CommunicationControl/DevOpsProject/Dockerfile ./src/CommunicationControl/DevOpsProject
          docker push $ECR_REGISTRY/communication-control:$IMAGE_TAG
          
          docker build -t $ECR_REGISTRY/hive-mind:$IMAGE_TAG -f ./src/CommunicationControl/DevOpsProject.HiveMind.API/Dockerfile ./src/CommunicationControl/DevOpsProject.HiveMind.API
          docker push $ECR_REGISTRY/hive-mind:$IMAGE_TAG
          
          docker build -t $ECR_REGISTRY/web:$IMAGE_TAG ./src/MapClient
          docker push $ECR_REGISTRY/web:$IMAGE_TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (needed for SCP)
        uses: actions/checkout@v4

      - name: Copy monitoring configs to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ github.ref_name == 'main' && secrets.HOST_MAIN || secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/monitoring/*" 
          target: "~/app/monitoring/"
          strip_components: 2
          rm: true

      - name: SSH and Update EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ github.ref_name == 'main' && secrets.HOST_MAIN || secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          overwrite: true
          script: |
            mkdir -p ~/app/monitoring
            cd ~/app
            FILE_NAME="docker-compose.${{ github.ref_name }}.yml"
            curl -L -o $FILE_NAME https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/src/$FILE_NAME
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 859384797868.dkr.ecr.us-east-1.amazonaws.com
            
            docker-compose -f $FILE_NAME pull
            docker-compose -f $FILE_NAME up -d
            docker image prune -af